# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 972cf2bbbfd13f3d697023cfabf71599675515904d2652eb028c36000daf3bbf849a74548d1ed713ee7cf6f5cf5e16fe258ce5a52920b96aecc92a060e3f9409

test:
  secret_key_base: 5cb0b24ea37830db75824729a9a8550031aa8a72e62ada72d7a82905ec108b6773efff6476c896a079c08f5e31f5c5b53e584fe2d79ae327af141af7d2636a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
